---
- name: Configure Centos/7 with WebLogic 12c R2 domain
  hosts: weblogic
  become: true
  become_user: "root"
  become_method: "sudo"
  vars_files:
    - infra-vars.yml
    - wls-vars.yml
  roles:
    - role: find-number-of-wls-managed-nodes
    - role: prepare-wls-env
    - role: install-jdk
    - role: install-wls
      become: true
      become_user: "{{ oracle_user}}"        
    - role: create-domain
      become: true
      become_user: "{{ oracle_user}}"    
    - role: setup-node-manager   
    - role: start-admin-server
      become: true
      become_user: "{{ oracle_user}}"
    - role: start-managed-servers
      become: true
      become_user: "{{ oracle_user}}"  