---
- name: "execute Weblogic installer"
  command: >- 
    {{ jdk_folder }}/bin/java -Xms1024m -Xmx1024m 
    -jar {{ wls_installer_folder }}/{{ wls_installation_archive }} 
    -silent -responseFile {{ wls_installer_folder }}/silent-weblogic.txt 
    -invPtrLoc {{ wls_installer_folder }}/oraInst.loc
  register: wlsInstallOutput  
- name: "Debug - wlsInstallOutput"
  debug:
    var: wlsInstallOutput
  tags: "debug"        