---
- name: "Copy Nodemanager Properties file"
  template: 
    src: "nodemanager.properties"
    dest: "{{ wls_domain_home }}/nodemanager/"
    owner: "{{ oracle_user}}"
    group: "{{ oracle_group }}"
  tags:
    - start-nodemanager
- name: "Copy nodemanager systemd script"
  template: 
    src: "nodemanager.service" 
    dest: "/etc/systemd/system/"
    mode: "0664"
  tags:
    - "start-nodemanager"
- name: "Enable nodemanager as linux service"
  command: "systemctl enable nodemanager"
  tags:
    - "start-nodemanager"
- name: "Start Node Manager"
  command: "systemctl start nodemanager"
  tags:
    - "start-nodemanager"
  register: "startNodeManagerOutput"
- name: "Debug - startNodeManagerOutput"
  debug:
    var: startNodeManagerOutput    
- name: "Waiting for nodemanager to come up"
  wait_for: 
    host: "{{ node_manager_listen_address }}" 
    port: "{{ node_manager_listen_port }}"
    delay: 2
    timeout: 30
  tags:
    - "start-nodemanager"