---
- name: "Copy Start Managed Server Script"
  template: 
    src: "start-managed-server.py" 
    dest: "{{ wls_installer_folder }}"
- name: "Start Managed Server"
  shell: "{{ weblogic_home }}/common/bin/wlst.sh {{ wls_installer_folder }}/start-managed-server.py"
  register: "startManagedNodeOutput"
- name: "Debug - startManagedNodeOutput"
  debug:
    var: startManagedNodeOutput 
  tags: "debug"  
- name: "Wait for Managed Servers to startup" 
  wait_for: 
    host: "{{ vars['vm' + item + '_ip_public'] }}" 
    port: "{{ ms_port_base }}{{ item }}" 
    delay: 2 
    timeout: 30
  with_sequence: "count={{ ms_count }}"  
  