---
# Start with env preps
- name: "Install required libraries"
  yum: 
    name: "{{ item }}" 
    state: "present"
  with_items: "{{ packages_list }}"
- name: "Disable SELinux"
  selinux: 
    state: "disabled"
- name: "Disable Firewall Deamon (firewalld)"
  service: 
    name: "firewalld" 
    state: "stopped" 
    enabled: "no"      
- name: "Change kernel parameters"
  sysctl: 
    name: "{{ item.key }}" 
    value: "{{ item.value }}" 
    state: "present"
  with_dict: "{{ kernel_params }}"
- name: "Create groups"
  group: 
    name: "{{ oracle_group }}"
    state: "present"
  register: "createOracleGroupOutput"
- name: "Debug - createOracleGroupOutput"  
  debug:
    var: "createOracleGroupOutput"
  tags: "debug"        
- name: "Create user"
  user: 
    name: "{{ oracle_user}}"
    groups: "{{ oracle_group }}" 
    password: "{{ oracle_os_user_pass  | password_hash('sha512') }}"
  register: "createOracleUserOutput"
- name: "Debug - createOracleUserOutput"  
  debug:
    var: "createOracleUserOutput"
  tags: "debug"    

# Add open file and process limits for oracle user
- name: "Create a shell profile with file and process limits for oracle user"
  template: 
    src: "oracle-limits.sh" 
    dest: "/etc/profile.d/"

# Add limits for oracle user
- name: "Add oracle user limits"
  lineinfile: 
    dest: "/etc/security/limits.conf"
    line: "'{{ oracle_user}} {{ item.limit }} {{ item.type}} {{ item.value }}'"
  with_items:
    - { limit: 'soft', type: nofile, value: '{{ soft_no_file }}' }
    - { limit: 'hard', type: nofile, value: '{{ hard_no_file }}' }
    - { limit: 'soft', type: nproc, value: '{{ soft_nproc }}' }
    - { limit: 'hard', type: nproc, value: '{{ hard_nproc }}' }

# Create Base Directories
- name: "Create Oracle Home directory"
  file: 
    state: "directory" 
    path: "{{ middleware_home }}" 
    owner: "{{ oracle_user}}" 
    group: "{{ oracle_group }}"
  register: "createOracleHomeDirectoryOutput"  
- name: "Debug - createOracleHomeDirectoryOutput"  
  debug:
    var: "createOracleHomeDirectoryOutput"
  tags: "debug"    
- name: "Create Domain Home directory"
  file: 
    state: "directory" 
    path: "{{ domains_home }}" 
    owner: "{{ oracle_user}}" 
    group: "{{ oracle_group }}"
  register: "createDomainHomeDirectoryOutput"      
- name: "Debug - createDomainHomeDirectoryOutput"  
  debug:
    var: "createDomainHomeDirectoryOutput"
  tags: "debug"    
- name: "Create Applications Home directory"
  file: 
    state: "directory"
    path: "{{ applications_home }}" 
    owner: "{{ oracle_user}}"
    group: "{{ oracle_group }}"
  register: "createApplicationHomeDirectoryOutput"          
- name: "Debug - createApplicationHomeDirectoryOutput"  
  debug:
    var: "createApplicationHomeDirectoryOutput"
  tags: "debug"      

# Prepare Wls Installer
- name: "Create installer directory"
  file: 
    state: "directory" 
    path: "{{ wls_installer_folder }}"
    owner: "{{ oracle_user}}" 
    group: "{{ oracle_group }}"     
- name: "Copy Middleware Installer"
  copy: 
    src: "{{ wls_installation_archive }}"
    dest: "{{ wls_installer_folder }}"
    owner: "{{ oracle_user}}" 
    group: "{{ oracle_group }}" 
  register: "copyWlsInstallerOutput"  
- name: "Debug - copyWlsInstallerOutput"
  debug:
    var: copyWlsInstallerOutput
  tags: "debug"  
- name: "Copy file for silent installation"
  template: 
    src: "silent-weblogic.txt" 
    dest: "{{ wls_installer_folder }}"
  register: "copyWlsSilentInstallFileOutput"
- name: "Debug - copyWlsSilentInstallFileOutput"
  debug:
    var: copyWlsSilentInstallFileOutput
  tags: "debug"    
- name: "Copy OraInst.loc"
  template: 
    src: "oraInst.loc" 
    dest: "{{ wls_installer_folder }}"
  register: "oraInstOutput"  
- name: "Debug - oraInstOutput"
  debug:
    var: oraInstOutput
  tags: "debug"    